<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Incorrect dob' => 'Некорректная дата рождения',
    'Incorrect phone' => 'Некорректно задан телефон',
    'Incorrect firstname' => 'Некорректно задано имя',
    'Incorrect lastname' => 'Некорректно задана фамилия',
    'Incorrect patronymic' => 'Некорректно задано отчество',
    'Enter dob' => 'Введите дату рождения',
    'User ID' => 'ID пользователя',
    'Avatar' => 'Аватар',
    'Firstname' => 'Имя',
    'Lastname' => 'Фамилия',
    'Patronymic' => 'Отчество',
    'Dob' => 'Дата рождения',
    'Phone' => 'Номер телефона',
    'Sex' => 'Пол',
    'Comment' => 'О себе',
    'Job' => 'Должность',
    'Social' => 'Ссылки на соц. сети',
    'Avatar Delete' => 'Удалить аватар?'
];