<?php

namespace chieff\modules\UserProfile\models;

use chieff\helpers\SecurityHelper;
use chieff\modules\UserProfile\UserProfileModule;
use Yii;
use webvimark\modules\UserManagement\models\User;

/**
 * This is the model class for table "user_profile".
 *
 * @property int $id
 * @property int $user_id
 * @property string $avatar
 * @property string $firstname
 * @property string $lastname
 * @property string $patronymic
 * @property int $dob
 * @property string $phone
 * @property int $sex
 */
class UserProfile extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user_profile';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'firstname', 'lastname', 'patronymic', 'dob', 'phone', 'sex'], 'required'],
            [['user_id', 'sex'], 'integer'],
            ['dob', 'validateDob'],
            ['phone', 'validatePhone'],
            [['phone'], 'string', 'max' => 20],
            [['firstname', 'lastname', 'patronymic'], 'validateName'],
            [['firstname', 'lastname', 'patronymic'], 'string', 'min' => 2, 'max' => 100],
            [['avatar'], 'string', 'max' => 100],
        ];
    }

    public function validateDob()
    {
        if ($this->dob) {
            $date = strtotime($this->dob);
            if ($date === false) {
                $this->addError('dob', UserProfileModule::t('front', 'Incorrect dob'));
            }
        }
    }

    public function validatePhone()
    {
        if ($this->phone) {
            if (preg_match('/' . Yii::$app->getModule('user-profile')->phoneRegexp . '/', $this->phone) !== 1) {
                $this->addError('phone', UserProfileModule::t('front', 'Incorrect phone'));
            }
        }
    }

    public function validateName()
    {
        if ($this->firstname) {
            if (preg_match('/[A-Za-zА-Яа-я]{2,}/', $this->firstname) !== 1) {
                $this->addError('firstname', UserProfileModule::t('front', 'Incorrect firstname'));
            }
        }
        if ($this->lastname) {
            if (preg_match('/[A-Za-zА-Яа-я]{2,}/', $this->lastname) !== 1) {
                $this->addError('lastname', UserProfileModule::t('front', 'Incorrect lastname'));
            }
        }
        if ($this->patronymic) {
            if (preg_match('/[A-Za-zА-Яа-я]{2,}/', $this->patronymic) !== 1) {
                $this->addError('patronymic', UserProfileModule::t('front', 'Incorrect patronymic'));
            }
        }
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => UserProfileModule::t('front', 'User ID'),
            'avatar' => UserProfileModule::t('front', 'Avatar'),
            'firstname' => UserProfileModule::t('front', 'Firstname'),
            'lastname' => UserProfileModule::t('front', 'Lastname'),
            'patronymic' => UserProfileModule::t('front', 'Patronymic'),
            'dob' => UserProfileModule::t('front', 'Dob'),
            'phone' => UserProfileModule::t('front', 'Phone'),
            'sex' => UserProfileModule::t('front', 'Sex'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getAvatar()
    {
        if (Yii::$app->getModule('user-profile')->encodeAvatar) {
            $file_alias = Yii::getAlias('@webroot');
            $file_full_path = $file_alias . $this->avatar;
            return SecurityHelper::getImageContent($file_full_path, true, 'aes-256-ctr', Yii::$app->getModule('user-profile')->passphrase);
        }
        return $this->avatar;
    }

    public function beforeSave($insert)
    {
        if (
            $this->dob &&
            !is_numeric($this->dob)
        ) {
            $date = strtotime($this->dob);
            if ($date !== false) {
                $this->dob = $date;
            } else {
                $this->dob = null;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function beforeDelete()
    {
        if ($this->avatar) {
            $file = Yii::getAlias('@webroot' . '/uploads/avatars/' . $this->avatar);
            if (
                $file &&
                file_exists($file)
            ) {
                unset($file);
            }
        }
        return parent::beforeDelete();
    }

}